name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project
      LLVM_PROFILE_FILE: "%p-%m.profraw"
      RUSTC_BOOTSTRAP: "1"
      RUSTFLAGS: "-Zinstrument-coverage"
    steps:
      - uses: actions/checkout@v2
      - name: Use Rust nightly
        run: rustup default nightly
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Compute coverage
        run: |
          rustup component add llvm-tools-preview
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
          ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - uses: codecov/codecov-action@v2
  publish:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Rust nightly
        run: rustup default nightly
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
